package zw.co.innbucks.loans.security;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpMethod;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.security.web.servlet.util.matcher.PathPatternRequestMatcher;
import org.springframework.security.web.util.matcher.RequestMatcher;
import org.springframework.web.filter.OncePerRequestFilter;
import zw.co.innbucks.loans.core.auth.JwtService;
import zw.co.innbucks.loans.web.ApiPaths;

import java.io.IOException;

/**
 * A session signed in on a temporary password may change that password and nothing else. Sign-in used to
 * report {@code temporaryPassword: true} and then accept the token everywhere, so a password generated by the
 * system, and sent by SMS or email, stayed a working credential for as long as its holder never changed it.
 *
 * <p>Runs in the authenticated chain right after the bearer token is authenticated, so it only ever sees a
 * token the decoder accepted; sign-in, the API docs and the health probes are on the unsecured chain and never
 * reach it. Which tokens are restricted is read from the token itself ({@link JwtService#TEMPORARY_PASSWORD_CLAIM}),
 * not the database: a password change bumps {@code token_version}, so a restricted token dies with the temporary
 * password it was minted on and the claim cannot outlive the flag. A token from before the claim existed carries
 * none and stays unrestricted until it expires.</p>
 *
 * <p>Deliberately not a bean: Spring Boot would register a {@code Filter} bean on every request, outside the
 * security chain, where no token has been authenticated yet.</p>
 */
@Slf4j
final class TemporaryPasswordFilter extends OncePerRequestFilter {

    /** The one call a restricted session may make. */
    private static final RequestMatcher CHANGE_PASSWORD =
            PathPatternRequestMatcher.withDefaults().matcher(HttpMethod.PUT, ApiPaths.BASE + "/me/password");

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain)
            throws ServletException, IOException {
        Authentication authentication = SecurityContextHolder.getContextHolderStrategy().getContext().getAuthentication();
        if (authentication instanceof JwtAuthenticationToken token
                && JwtService.issuedOnTemporaryPassword(token.getToken())
                && !CHANGE_PASSWORD.matches(request)) {
            log.info("Refused {} {} for {}: signed in on a temporary password, which must be changed first",
                    request.getMethod(), request.getRequestURI(), token.getToken().getClaimAsString("preferred_username"));
            SecurityErrorResponses.passwordChangeRequired(response);
            return;
        }
        chain.doFilter(request, response);
    }
}
