-- Employment events (FR-SSB-024): what happened to a borrower's employment, and what that did to their loans.
-- An event is recorded against an EC number; the treatment configured for its type is applied to every open
-- application and loan under that EC number, and each loan keeps a record of what was done to it.

-- The treatment of each type of event, changed by an administrator without a release. For applications not
-- yet paid out: CONTINUE, HOLD (kept from lodgement, credit approval and booking until an officer releases or
-- declines it) or DECLINE. For loans already paid out: NONE or REVIEW (opened for an officer to decide how the
-- loan will be repaid). notify_on_decline: whether a declined applicant is sent the decline SMS.
CREATE TABLE employment_event_treatments (
    event_type            VARCHAR(32)  NOT NULL,
    application_treatment VARCHAR(16)  NOT NULL,
    loan_treatment        VARCHAR(16)  NOT NULL,
    notify_on_decline     BOOLEAN      NOT NULL,
    updated_by            VARCHAR(255) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    CONSTRAINT employment_event_treatments_pkey PRIMARY KEY (event_type),
    CONSTRAINT ck_employment_event_treatments_event_type CHECK (event_type IN ('TRANSFER', 'SECONDMENT',
        'PROMOTION', 'SUSPENSION', 'UNPAID_LEAVE', 'RESIGNATION', 'RETIREMENT', 'DEATH_IN_SERVICE')),
    CONSTRAINT ck_employment_event_treatments_application CHECK (application_treatment IN ('CONTINUE', 'HOLD', 'DECLINE')),
    CONSTRAINT ck_employment_event_treatments_loan CHECK (loan_treatment IN ('NONE', 'REVIEW'))
);

-- Defaults, for the bank to change. A move within the civil service keeps the payroll deduction; anything that
-- stops or may stop the salary holds the application for an officer and opens paid loans for review; leaving
-- the service declines the application outright, and a death in service does so without messaging the phone.
INSERT INTO employment_event_treatments
    (event_type, application_treatment, loan_treatment, notify_on_decline, updated_by, updated_at)
VALUES ('TRANSFER',         'CONTINUE', 'NONE',   TRUE,  'system', now() AT TIME ZONE 'UTC'),
       ('PROMOTION',        'CONTINUE', 'NONE',   TRUE,  'system', now() AT TIME ZONE 'UTC'),
       ('SECONDMENT',       'HOLD',     'REVIEW', TRUE,  'system', now() AT TIME ZONE 'UTC'),
       ('SUSPENSION',       'HOLD',     'REVIEW', TRUE,  'system', now() AT TIME ZONE 'UTC'),
       ('UNPAID_LEAVE',     'HOLD',     'REVIEW', TRUE,  'system', now() AT TIME ZONE 'UTC'),
       ('RETIREMENT',       'HOLD',     'REVIEW', TRUE,  'system', now() AT TIME ZONE 'UTC'),
       ('RESIGNATION',      'DECLINE',  'REVIEW', TRUE,  'system', now() AT TIME ZONE 'UTC'),
       ('DEATH_IN_SERVICE', 'DECLINE',  'REVIEW', FALSE, 'system', now() AT TIME ZONE 'UTC');

-- One event in a borrower's employment. ministry, station and grade are the new ones, for a transfer,
-- secondment or promotion; end_date is when a secondment, suspension or unpaid leave ends, when known.
-- Never changed once recorded.
CREATE TABLE employment_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ec_number      VARCHAR(16)  NOT NULL,
    event_type     VARCHAR(32)  NOT NULL,
    effective_date DATE         NOT NULL,
    end_date       DATE,
    ministry       VARCHAR(255),
    station        VARCHAR(255),
    grade          VARCHAR(64),
    note           VARCHAR(500),
    recorded_by    VARCHAR(255) NOT NULL,
    recorded_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT employment_events_pkey PRIMARY KEY (id),
    CONSTRAINT uq_employment_events_occurrence UNIQUE (ec_number, event_type, effective_date),
    CONSTRAINT ck_employment_events_event_type CHECK (event_type IN ('TRANSFER', 'SECONDMENT', 'PROMOTION',
        'SUSPENSION', 'UNPAID_LEAVE', 'RESIGNATION', 'RETIREMENT', 'DEATH_IN_SERVICE')),
    CONSTRAINT ck_employment_events_end_date CHECK (end_date IS NULL OR end_date >= effective_date)
);
CREATE INDEX idx_employment_events_ec_number ON employment_events (ec_number, id);

CREATE TRIGGER trg_employment_events_append_only
    BEFORE UPDATE OR DELETE ON employment_events
    FOR EACH ROW EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_employment_events_no_truncate
    BEFORE TRUNCATE ON employment_events
    FOR EACH STATEMENT EXECUTE FUNCTION refuse_append_only_change();

-- What an event did to one loan. NONE and DECLINE are settled when the event is recorded; HOLD and REVIEW stay
-- OPEN in the officers' queue until resolved, once: a hold RELEASED or DECLINED, a review REVIEWED.
CREATE TABLE loan_employment_events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id          BIGINT       NOT NULL,
    loan_id           BIGINT       NOT NULL,
    action            VARCHAR(16)  NOT NULL,
    notify_on_decline BOOLEAN      NOT NULL,
    status            VARCHAR(16)  NOT NULL,
    outcome           VARCHAR(16),
    comment           VARCHAR(500),
    resolved_by       VARCHAR(255),
    resolved_at       TIMESTAMP(6),
    created_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT loan_employment_events_pkey PRIMARY KEY (id),
    CONSTRAINT fk_loan_employment_events_event_id FOREIGN KEY (event_id) REFERENCES employment_events (id),
    CONSTRAINT fk_loan_employment_events_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT uq_loan_employment_events_event_loan UNIQUE (event_id, loan_id),
    CONSTRAINT ck_loan_employment_events_action CHECK (action IN ('NONE', 'HOLD', 'DECLINE', 'REVIEW')),
    CONSTRAINT ck_loan_employment_events_status CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_loan_employment_events_outcome CHECK (outcome IN ('RELEASED', 'DECLINED', 'REVIEWED')),
    -- Only a hold or a review waits for an officer, and an open one has no outcome yet.
    CONSTRAINT ck_loan_employment_events_open CHECK (status = 'CLOSED'
        OR (action IN ('HOLD', 'REVIEW') AND outcome IS NULL AND resolved_at IS NULL)),
    -- Anything closed but a NONE says how it ended.
    CONSTRAINT ck_loan_employment_events_closed CHECK (status = 'OPEN' OR action = 'NONE' OR outcome IS NOT NULL)
);
CREATE INDEX idx_loan_employment_events_loan_id ON loan_employment_events (loan_id);
CREATE INDEX idx_loan_employment_events_open ON loan_employment_events (id) WHERE status = 'OPEN';
CREATE INDEX idx_loan_employment_events_hold ON loan_employment_events (loan_id)
    WHERE status = 'OPEN' AND action = 'HOLD';

-- A loan's record may be resolved once, and nothing else about it ever changes; none is ever removed.
CREATE FUNCTION refuse_loan_employment_event_change() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    IF OLD.status <> 'OPEN' OR NEW.status <> 'CLOSED'
        OR NEW.event_id <> OLD.event_id OR NEW.loan_id <> OLD.loan_id OR NEW.action <> OLD.action
        OR NEW.notify_on_decline <> OLD.notify_on_decline OR NEW.created_at <> OLD.created_at THEN
        RAISE EXCEPTION 'loan_employment_events % may only be resolved, once', OLD.id;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_loan_employment_events_resolve_once
    BEFORE UPDATE ON loan_employment_events
    FOR EACH ROW EXECUTE FUNCTION refuse_loan_employment_event_change();
CREATE TRIGGER trg_loan_employment_events_no_delete
    BEFORE DELETE ON loan_employment_events
    FOR EACH ROW EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_loan_employment_events_no_truncate
    BEFORE TRUNCATE ON loan_employment_events
    FOR EACH STATEMENT EXECUTE FUNCTION refuse_append_only_change();
