-- Checkpoint stages (FR-SSB-014): stages an administrator adds without a release. A checkpoint holds each loan it
-- applies to at one point in the lifecycle until someone who works it clears or declines the loan:
--   BEFORE_LODGEMENT       the deduction is not lodged with SSB;
--   BEFORE_CREDIT_APPROVAL Credit cannot approve the application;
--   BEFORE_BOOKING         the loan is not booked with InnBucks, which pays it out.
-- It applies to every loan reaching that point, or only to those at or above a principal or from given channels.
-- Deactivating it lifts its hold at once; it cannot be deleted, because its decisions refer to it.
ALTER TABLE workflow_stages DROP CONSTRAINT ck_workflow_stages_kind;
ALTER TABLE workflow_stages ADD CONSTRAINT ck_workflow_stages_kind CHECK (kind IN ('SYSTEM', 'CHECKPOINT'));

ALTER TABLE workflow_stages ADD COLUMN hold_point VARCHAR(32);
ALTER TABLE workflow_stages ADD COLUMN minimum_principal NUMERIC(19, 2);
ALTER TABLE workflow_stages ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
-- When the checkpoint last became active: a loan already at its point then waits from this moment.
ALTER TABLE workflow_stages ADD COLUMN active_since TIMESTAMP(6);

ALTER TABLE workflow_stages ADD CONSTRAINT ck_workflow_stages_hold_point
    CHECK (hold_point IN ('BEFORE_LODGEMENT', 'BEFORE_CREDIT_APPROVAL', 'BEFORE_BOOKING'));
ALTER TABLE workflow_stages ADD CONSTRAINT ck_workflow_stages_minimum_principal
    CHECK (minimum_principal IS NULL OR minimum_principal > 0);
-- A system stage is always active and holds nothing of its own; a checkpoint always has a point and an activation.
ALTER TABLE workflow_stages ADD CONSTRAINT ck_workflow_stages_checkpoint
    CHECK ((kind = 'SYSTEM' AND hold_point IS NULL AND minimum_principal IS NULL AND active AND active_since IS NULL)
        OR (kind = 'CHECKPOINT' AND hold_point IS NOT NULL AND active_since IS NOT NULL));

-- The channels a checkpoint is limited to (a channel's channel_id, or PORTAL for applications captured on the
-- portal with no channel); none means every channel.
CREATE TABLE workflow_stage_channels (
    stage_code VARCHAR(40)  NOT NULL,
    channel_id VARCHAR(255) NOT NULL,
    CONSTRAINT workflow_stage_channels_pkey PRIMARY KEY (stage_code, channel_id),
    CONSTRAINT fk_workflow_stage_channels_stage FOREIGN KEY (stage_code) REFERENCES workflow_stages (code)
);

-- How each loan left a checkpoint: CLEARED (it carries on) or DECLINED (a credit rejection, with its reason code, in
-- the credit decision log as well). One per checkpoint and loan. Append-only.
CREATE TABLE checkpoint_decisions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    stage_code  VARCHAR(40)  NOT NULL,
    loan_id     BIGINT       NOT NULL,
    entered_at  TIMESTAMP(6) NOT NULL,
    outcome     VARCHAR(16)  NOT NULL,
    reason_code VARCHAR(64),
    comment     VARCHAR(255) NOT NULL,
    decided_by  VARCHAR(255) NOT NULL,
    decided_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT checkpoint_decisions_pkey PRIMARY KEY (id),
    CONSTRAINT fk_checkpoint_decisions_stage FOREIGN KEY (stage_code) REFERENCES workflow_stages (code),
    CONSTRAINT fk_checkpoint_decisions_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT fk_checkpoint_decisions_reason_code FOREIGN KEY (reason_code) REFERENCES credit_reason_codes (code),
    CONSTRAINT uq_checkpoint_decisions_stage_loan UNIQUE (stage_code, loan_id),
    CONSTRAINT ck_checkpoint_decisions_outcome CHECK (outcome IN ('CLEARED', 'DECLINED')),
    CONSTRAINT ck_checkpoint_decisions_reason_code CHECK ((outcome = 'DECLINED') = (reason_code IS NOT NULL))
);
CREATE INDEX idx_checkpoint_decisions_loan_id ON checkpoint_decisions (loan_id);
CREATE INDEX idx_checkpoint_decisions_decided_at ON checkpoint_decisions (decided_at);
CREATE TRIGGER trg_checkpoint_decisions_append_only
    BEFORE UPDATE OR DELETE ON checkpoint_decisions
    FOR EACH ROW EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_checkpoint_decisions_no_truncate
    BEFORE TRUNCATE ON checkpoint_decisions
    FOR EACH STATEMENT EXECUTE FUNCTION refuse_append_only_change();
