-- ============================================================================
-- The loans schema, created on an empty database.
--
-- Naming: tables are plural snake_case, columns snake_case. Constraints are
-- <table>_pkey, fk_<table>_<column>, uq_<table>_<columns> and ck_<table>_<column>;
-- indexes are idx_<table>_<columns>. A database Hibernate built before Flyway
-- (ddl-auto: update) is baselined at this version and upgraded by V2 instead.
--
-- Timestamps are UTC (the containers pin -Duser.timezone=UTC and the code writes
-- LocalDateTime.now(ZoneOffset.UTC)); money is numeric in major units.
-- ============================================================================

CREATE TABLE commission_groups (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    agent_commission    NUMERIC(38,2),
    enabled             BOOLEAN NOT NULL,
    name                VARCHAR(255),
    percentage          BOOLEAN NOT NULL,
    provider_commission NUMERIC(38,2),
    created_date        TIMESTAMP(6) NOT NULL,
    last_modified_date  TIMESTAMP(6),
    version             BIGINT NOT NULL,
    CONSTRAINT commission_groups_pkey PRIMARY KEY (id),
    CONSTRAINT uq_commission_groups_name UNIQUE (name)
);

CREATE TABLE merchants (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_number               VARCHAR(255),
    commission_structure         VARCHAR(255),
    name                         VARCHAR(255),
    contact_person_email         VARCHAR(255),
    contact_person_mobile_number VARCHAR(255),
    contact_person_name          VARCHAR(255),
    disbursement_type            VARCHAR(255),
    merchant_code                VARCHAR(255),
    physical_address             VARCHAR(255),
    commission_group_id          BIGINT,
    created_date                 TIMESTAMP(6) NOT NULL,
    last_modified_date           TIMESTAMP(6),
    version                      BIGINT NOT NULL,
    CONSTRAINT merchants_pkey PRIMARY KEY (id),
    CONSTRAINT ck_merchants_commission_structure CHECK (commission_structure IN ('AGENT_DEFINED','MERCHANT_DEFINED')),
    CONSTRAINT ck_merchants_disbursement_type CHECK (disbursement_type IN ('CUSTOMER_MOBILE_WALLET','MERCHANT_MOBILE_WALLET'))
);
CREATE INDEX idx_merchants_merchant_code ON merchants (merchant_code);

CREATE TABLE users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email                 VARCHAR(255),
    external_system_id    VARCHAR(100) NOT NULL,
    failed_login_attempts INTEGER,
    first_name            VARCHAR(255),
    id_number             VARCHAR(255),
    last_name             VARCHAR(255),
    locked_until          TIMESTAMP(6),
    mobile_number         VARCHAR(255),
    password              VARCHAR(255),
    physical_address      VARCHAR(255),
    temporary_password    BOOLEAN NOT NULL,
    token_version         BIGINT,
    username              VARCHAR(100) NOT NULL,
    commission_group_id   BIGINT,
    merchant_id           BIGINT NOT NULL,
    created_date          TIMESTAMP(6) NOT NULL,
    last_modified_date    TIMESTAMP(6),
    version               BIGINT NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uq_users_external_system_id UNIQUE (external_system_id),
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE user_groups (
    user_id    BIGINT NOT NULL,
    user_group VARCHAR(255) NOT NULL,
    CONSTRAINT user_groups_pkey PRIMARY KEY (user_id, user_group),
    CONSTRAINT ck_user_groups_user_group CHECK (user_group IN ('AGENTS','SUPER_ADMIN','CREDIT_MANAGER','FINANCE'))
);

CREATE TABLE channels (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    channel_id         VARCHAR(255),
    name               VARCHAR(255),
    system_user_id     BIGINT,
    created_date       TIMESTAMP(6) NOT NULL,
    last_modified_date TIMESTAMP(6),
    version            BIGINT NOT NULL,
    CONSTRAINT channels_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_channels_channel_id ON channels (channel_id);

CREATE TABLE loans (
    id                                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    city                                 VARCHAR(255),
    country                              VARCHAR(255),
    street                               VARCHAR(255),
    suburb                               VARCHAR(255),
    agent_commission                     NUMERIC(38,2),
    agent_commission_rate                NUMERIC(38,2),
    alternate_contact_number             VARCHAR(255),
    approval_attempt                     INTEGER,
    approval_reference                   VARCHAR(255),
    approved_disbursement_type           VARCHAR(255),
    approved_settlement_account          VARCHAR(255),
    bank_account_name                    VARCHAR(255),
    bank_account_number                  VARCHAR(255),
    bank_account_type                    VARCHAR(255),
    bank_name                            VARCHAR(255),
    bank_branch_code                     VARCHAR(255),
    bank_branch_name                     VARCHAR(255),
    batch_number                         VARCHAR(255),
    booking_claimed_at                   TIMESTAMP(6),
    booking_failure_kind                 VARCHAR(255),
    booking_not_found_at                 TIMESTAMP(6),
    commission_rate                      NUMERIC(38,2),
    commission_rate_percentage           BOOLEAN,
    created_by                           VARCHAR(255),
    date_approved                        TIMESTAMP(6),
    date_disbursed                       TIMESTAMP(6),
    date_of_birth                        DATE,
    deduction_cancellation_note          VARCHAR(255),
    deduction_cancellation_reason        VARCHAR(255),
    deduction_cancellation_requested_at  TIMESTAMP(6),
    deduction_cancellation_status        VARCHAR(255),
    deduction_cancelled_at               TIMESTAMP(6),
    deduction_cancelled_by               VARCHAR(255),
    disbursed_amount                     NUMERIC(38,2),
    disbursement_attempts                INTEGER,
    disbursement_merchant_account_number VARCHAR(255),
    disbursement_reference               VARCHAR(255),
    disbursement_status                  VARCHAR(255),
    disbursement_status_message          VARCHAR(255),
    ec_number                            VARCHAR(255),
    education_level                      VARCHAR(255),
    email                                VARCHAR(255),
    employer_city                        VARCHAR(255),
    employer_country                     VARCHAR(255),
    employer_street                      VARCHAR(255),
    employer_suburb                      VARCHAR(255),
    employee_number                      VARCHAR(255),
    employer_contact_number              VARCHAR(255),
    employer_name                        VARCHAR(255),
    employment_end_date                  DATE,
    employment_start_date                DATE,
    gross_salary                         NUMERIC(38,2),
    net_salary                           NUMERIC(38,2),
    fee_amount                           NUMERIC(38,2),
    fee_rate                             NUMERIC(38,2),
    first_name                           VARCHAR(255),
    gender                               VARCHAR(255),
    grossed_monthly_deduction            NUMERIC(38,2),
    interest_amount                      NUMERIC(38,2),
    interest_rate                        NUMERIC(38,2),
    internal_approval_by                 VARCHAR(255),
    internal_approval_comment            VARCHAR(255),
    internal_approval_date               TIMESTAMP(6),
    internal_approval_status             VARCHAR(255),
    last_name                            VARCHAR(255),
    line_of_business                     VARCHAR(255),
    loan_account_status                  VARCHAR(255),
    loan_status                          VARCHAR(255),
    loan_end_date                        DATE,
    loan_purpose                         VARCHAR(255),
    loan_start_date                      DATE,
    loan_status_message                  VARCHAR(255),
    lodgement_claimed_at                 TIMESTAMP(6),
    marital_status                       VARCHAR(255),
    mobile_number                        VARCHAR(255),
    monthly_installment                  NUMERIC(38,2),
    national_id_number                   VARCHAR(255),
    national_id_picture                  TEXT,
    ndasenda_response_overdue_at         TIMESTAMP(6),
    next_disbursement_attempt_date       TIMESTAMP(6),
    next_lodgement_attempt_at            TIMESTAMP(6),
    next_of_kin_city                     VARCHAR(255),
    next_of_kin_country                  VARCHAR(255),
    next_of_kin_street                   VARCHAR(255),
    next_of_kin_suburb                   VARCHAR(255),
    next_of_kin_first_name               VARCHAR(255),
    next_of_kin_gender                   VARCHAR(255),
    next_of_kin_last_name                VARCHAR(255),
    next_of_kin_mobile_number            VARCHAR(255),
    next_of_kin_id_number                VARCHAR(255),
    next_of_kin_relationship             VARCHAR(255),
    number_of_children                   INTEGER,
    number_of_dependants                 INTEGER,
    payslip_picture                      TEXT,
    place_of_birth                       VARCHAR(255),
    principal                            NUMERIC(38,2),
    product_description                  VARCHAR(255),
    profession                           VARCHAR(255),
    provider_commission                  NUMERIC(38,2),
    provider_commission_rate             NUMERIC(38,2),
    public_reference                     VARCHAR(20),
    repayment_end_date                   DATE,
    repayment_start_date                 DATE,
    signature                            TEXT,
    tenor                                INTEGER,
    title                                VARCHAR(255),
    witness_date_signed                  DATE,
    witness_full_name                    VARCHAR(255),
    witness_place_of_signature           VARCHAR(255),
    witness_signature                    TEXT,
    channel_id                           BIGINT,
    created_by_user_id                   BIGINT,
    merchant_id                          BIGINT,
    created_date                         TIMESTAMP(6) NOT NULL,
    last_modified_date                   TIMESTAMP(6),
    version                              BIGINT NOT NULL,
    CONSTRAINT loans_pkey PRIMARY KEY (id),
    CONSTRAINT ck_loans_approved_disbursement_type CHECK (approved_disbursement_type IN ('CUSTOMER_MOBILE_WALLET','MERCHANT_MOBILE_WALLET')),
    CONSTRAINT ck_loans_bank_account_type CHECK (bank_account_type IN ('SAVINGS','CURRENT')),
    CONSTRAINT ck_loans_booking_failure_kind CHECK (booking_failure_kind IN ('REFUSED','AMBIGUOUS')),
    CONSTRAINT ck_loans_deduction_cancellation_status CHECK (deduction_cancellation_status IN ('REQUIRED','CANCELLED_EXTERNALLY')),
    CONSTRAINT ck_loans_disbursement_status CHECK (disbursement_status IN ('PENDING','FAILED','SUCCESS')),
    CONSTRAINT ck_loans_education_level CHECK (education_level IN ('PRIMARY','SECONDARY','O_LEVEL','A_LEVEL','NATIONAL_DIPLOMA','DEGREE','MASTERS','DOCTORATE')),
    CONSTRAINT ck_loans_gender CHECK (gender IN ('MALE','FEMALE')),
    CONSTRAINT ck_loans_internal_approval_status CHECK (internal_approval_status IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT ck_loans_line_of_business CHECK (line_of_business IN ('AGRICULTURE','ARTS_AND_ENTERTAINMENT','CONSTRUCTION','EDUCATION','ENERGY','FINANCIAL_SERVICES','GOVERNMENT','HEALTH','ICT','MANUFACTURING','MINING_AND_QUARRYING_ACTIVITIES','SERVICES','TOURISM_AND_HOSPITALITY','TRANSPORT_AND_STORAGE','WHOLESALE_AND_RETAIL')),
    CONSTRAINT ck_loans_loan_account_status CHECK (loan_account_status IN ('PENDING','FAILED','CREATED')),
    CONSTRAINT ck_loans_loan_purpose CHECK (loan_purpose IN ('PURCHASE_OF_ASSETS','BUSINESS_EXPANSION','CAPEX','DEBT_REFINANCING','HOME_IMPROVEMENT','MEDICAL','PREMIUMS','PERSONAL_USE','VACATION','GENERAL_WORKING_CAPITAL','WEDDING_EXPENSES')),
    CONSTRAINT ck_loans_loan_status CHECK (loan_status IN ('NEW','PROCESSING','APPROVED','REJECTED','PAID','FAILED')),
    CONSTRAINT ck_loans_marital_status CHECK (marital_status IN ('SINGLE','MARRIED','DIVORCED','WIDOWED')),
    CONSTRAINT ck_loans_next_of_kin_gender CHECK (next_of_kin_gender IN ('MALE','FEMALE')),
    CONSTRAINT ck_loans_next_of_kin_relationship CHECK (next_of_kin_relationship IN ('SIBLING','DAUGHTER','SPOUSE','DAUGHTER_IN_LAW','FATHER','FATHER_IN_LAW','GUARDIAN','MOTHER','MOTHER_IN_LAW','NEPHEW','SISTER_IN_LAW','SON')),
    CONSTRAINT ck_loans_title CHECK (title IN ('MR','MRS','MISS','MS','DR','PROF'))
);
CREATE INDEX idx_loans_batch_number ON loans (batch_number);
CREATE INDEX idx_loans_ec_number ON loans (ec_number);

CREATE TABLE loan_batches (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_number       VARCHAR(255),
    created_date       TIMESTAMP(6) NOT NULL,
    last_modified_date TIMESTAMP(6),
    version            BIGINT NOT NULL,
    CONSTRAINT loan_batches_pkey PRIMARY KEY (id),
    CONSTRAINT uq_loan_batches_batch_number UNIQUE (batch_number)
);

CREATE TABLE loan_disbursements (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    date_disbursed              TIMESTAMP(6),
    disbursement_reference      VARCHAR(255),
    disbursement_status         VARCHAR(255),
    disbursement_status_message VARCHAR(255),
    loan_id                     BIGINT,
    created_date                TIMESTAMP(6) NOT NULL,
    last_modified_date          TIMESTAMP(6),
    version                     BIGINT NOT NULL,
    CONSTRAINT loan_disbursements_pkey PRIMARY KEY (id),
    CONSTRAINT ck_loan_disbursements_disbursement_status CHECK (disbursement_status IN ('PENDING','FAILED','SUCCESS'))
);

CREATE TABLE loan_sagas (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    compensated_at     TIMESTAMP(6),
    current_state      VARCHAR(40) NOT NULL,
    failure_reason     VARCHAR(512),
    flagged_anomaly    VARCHAR(40),
    last_transition_at TIMESTAMP(6) NOT NULL,
    loan_id            BIGINT NOT NULL,
    created_at         TIMESTAMP(6) NOT NULL,
    version            BIGINT NOT NULL,
    CONSTRAINT loan_sagas_pkey PRIMARY KEY (id),
    CONSTRAINT uq_loan_sagas_loan_id UNIQUE (loan_id),
    CONSTRAINT ck_loan_sagas_current_state CHECK (current_state IN ('SSB_VERIFICATION_PENDING','SSB_REJECTED','SSB_VERIFICATION_FAILED','CREDIT_ASSESSMENT_PENDING','CREDIT_REJECTED','CREDIT_APPROVED','DISBURSEMENT_PENDING','DISBURSED','DISBURSEMENT_FAILED','COMPENSATED'))
);
CREATE INDEX idx_loan_sagas_current_state ON loan_sagas (current_state);

CREATE TABLE ledger_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account         VARCHAR(48) NOT NULL,
    amount          NUMERIC(19,4) NOT NULL,
    created_by      VARCHAR(128),
    currency        VARCHAR(3) NOT NULL,
    description     VARCHAR(255),
    entry_type      VARCHAR(8) NOT NULL,
    loan_id         BIGINT,
    transaction_ref VARCHAR(64) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT ledger_entries_pkey PRIMARY KEY (id),
    CONSTRAINT ck_ledger_entries_entry_type CHECK (entry_type IN ('DEBIT','CREDIT')),
    CONSTRAINT ck_ledger_entries_account CHECK (account IN ('LOAN_PRINCIPAL_RECEIVABLE','DISBURSEMENT_CLEARING','FEE_INCOME','INTEREST_RECEIVABLE','AGENT_COMMISSION_PAYABLE','SSB_DEDUCTIONS_RECEIVABLE','REVERSAL_SUSPENSE')),
    CONSTRAINT uq_ledger_entries_transaction_ref_account_entry_type UNIQUE (transaction_ref, account, entry_type)
);
CREATE INDEX idx_ledger_entries_loan_id ON ledger_entries (loan_id);
CREATE INDEX idx_ledger_entries_account ON ledger_entries (account);
CREATE INDEX idx_ledger_entries_transaction_ref ON ledger_entries (transaction_ref);

CREATE TABLE audit_logs (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actor_id               VARCHAR(128),
    channel_used           VARCHAR(128),
    correlation_id         VARCHAR(128),
    detail                 TEXT,
    entity_id              VARCHAR(64),
    entity_type            VARCHAR(64),
    event_type             VARCHAR(64) NOT NULL,
    payload_hash           VARCHAR(64),
    state_transition_delta TEXT,
    created_at             TIMESTAMP(6) NOT NULL,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_audit_logs_entity_type_entity_id ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_logs_correlation_id ON audit_logs (correlation_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);

CREATE TABLE parameters (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_can_edit      BOOLEAN,
    name               VARCHAR(50),
    val                VARCHAR(200) NOT NULL,
    created_date       TIMESTAMP(6) NOT NULL,
    last_modified_date TIMESTAMP(6),
    version            BIGINT NOT NULL,
    CONSTRAINT parameters_pkey PRIMARY KEY (id),
    CONSTRAINT uq_parameters_name UNIQUE (name)
);

ALTER TABLE channels ADD CONSTRAINT fk_channels_system_user_id FOREIGN KEY (system_user_id) REFERENCES users (id);
ALTER TABLE loan_disbursements ADD CONSTRAINT fk_loan_disbursements_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id);
ALTER TABLE loans ADD CONSTRAINT fk_loans_channel_id FOREIGN KEY (channel_id) REFERENCES channels (id);
ALTER TABLE loans ADD CONSTRAINT fk_loans_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users (id);
ALTER TABLE loans ADD CONSTRAINT fk_loans_merchant_id FOREIGN KEY (merchant_id) REFERENCES merchants (id);
ALTER TABLE merchants ADD CONSTRAINT fk_merchants_commission_group_id FOREIGN KEY (commission_group_id) REFERENCES commission_groups (id);
ALTER TABLE user_groups ADD CONSTRAINT fk_user_groups_user_id FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE users ADD CONSTRAINT fk_users_commission_group_id FOREIGN KEY (commission_group_id) REFERENCES commission_groups (id);
ALTER TABLE users ADD CONSTRAINT fk_users_merchant_id FOREIGN KEY (merchant_id) REFERENCES merchants (id);


-- ----------------------------------------------------------------------------
-- What the entities cannot express
-- ----------------------------------------------------------------------------

-- The public loan reference (LN-2026-00042). Drawn by the saga when a loan is
-- disbursed; the internal zero-padded reference Ndasenda uses is separate.
CREATE SEQUENCE loan_public_ref_seq START WITH 1;
CREATE UNIQUE INDEX uq_loans_public_reference ON loans (public_reference) WHERE public_reference IS NOT NULL;

-- The pending-application check matches an applicant by EC number or national ID
-- compared upper-cased, which the plain index on ec_number cannot serve.
CREATE INDEX idx_loans_upper_ec_number ON loans (upper(ec_number));
CREATE INDEX idx_loans_upper_national_id_number ON loans (upper(national_id_number));

-- The ledger is append-only: a correction is a reversing entry, never an edit.
CREATE FUNCTION ledger_entries_immutable() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'ledger_entries is append-only: % is forbidden. Post a reversing entry instead.', TG_OP;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER trg_ledger_entries_immutable
    BEFORE UPDATE OR DELETE ON ledger_entries
    FOR EACH ROW EXECUTE FUNCTION ledger_entries_immutable();
