-- Credit decisions carry a reason code and a comment, a loan can be returned for more information,
-- and every credit action is kept in an append-only log with the data it was based on
-- (FR-SSB-015, applying FR-PBL-027, FR-PBL-029 and FR-PBL-032).

-- The reason codes a credit officer picks from. A code belongs to exactly one decision; an inactive
-- code stays for the history that names it but can no longer be chosen.
CREATE TABLE credit_reason_codes (
    code          VARCHAR(64)  NOT NULL,
    decision      VARCHAR(32)  NOT NULL,
    description   VARCHAR(255) NOT NULL,
    active        BOOLEAN      NOT NULL,
    display_order INTEGER      NOT NULL,
    CONSTRAINT credit_reason_codes_pkey PRIMARY KEY (code),
    CONSTRAINT ck_credit_reason_codes_decision CHECK (decision IN ('APPROVED', 'REJECTED', 'RETURNED'))
);

INSERT INTO credit_reason_codes (code, decision, description, active, display_order) VALUES
    ('APPROVE_WITHIN_POLICY',       'APPROVED', 'Meets credit policy',                              TRUE,  10),
    ('APPROVE_RISK_ACCEPTED',       'APPROVED', 'Outside a guideline, risk accepted; see comment',  TRUE,  20),
    ('LEGACY_APPROVAL',             'APPROVED', 'Approved before reason codes were recorded',       FALSE, 90),
    ('REJECT_AFFORDABILITY',        'REJECTED', 'Deduction capacity insufficient',                  TRUE,  10),
    ('REJECT_EMPLOYMENT',           'REJECTED', 'Employment not verified or not eligible',          TRUE,  20),
    ('REJECT_IDENTITY',             'REJECTED', 'Identity could not be verified',                   TRUE,  30),
    ('REJECT_DOCUMENTS',            'REJECTED', 'Documents invalid, unreadable or inconsistent',    TRUE,  40),
    ('REJECT_SUSPECTED_FRAUD',      'REJECTED', 'Suspected fraud or misrepresentation',             TRUE,  50),
    ('REJECT_CREDIT_HISTORY',       'REJECTED', 'Adverse credit history or existing exposure',      TRUE,  60),
    ('REJECT_CUSTOMER_REQUEST',     'REJECTED', 'Withdrawn at the customer''s request',             TRUE,  70),
    ('REJECT_OTHER',                'REJECTED', 'Other; see comment',                               TRUE,  80),
    ('LEGACY_REJECTION',            'REJECTED', 'Rejected before reason codes were recorded',       FALSE, 90),
    ('RETURN_PAYSLIP',              'RETURNED', 'Payslip missing, unclear or out of date',          TRUE,  10),
    ('RETURN_IDENTITY_DOCUMENT',    'RETURNED', 'National ID missing or unclear',                   TRUE,  20),
    ('RETURN_EMPLOYMENT_DETAIL',    'RETURNED', 'Employment details incomplete or inconsistent',    TRUE,  30),
    ('RETURN_APPLICANT_DETAIL',     'RETURNED', 'Applicant details incomplete or inconsistent',     TRUE,  40),
    ('RETURN_OTHER',                'RETURNED', 'Other; see comment',                               TRUE,  80);

-- A loan can now be returned to its originator for more information.
ALTER TABLE loans DROP CONSTRAINT ck_loans_internal_approval_status;
ALTER TABLE loans
    ADD CONSTRAINT ck_loans_internal_approval_status
        CHECK (internal_approval_status IN ('PENDING', 'APPROVED', 'REJECTED', 'RETURNED')),
    ADD COLUMN internal_approval_reason_code VARCHAR(64),
    ADD CONSTRAINT fk_loans_internal_approval_reason_code
        FOREIGN KEY (internal_approval_reason_code) REFERENCES credit_reason_codes (code);

-- Every credit action on a loan, oldest first by id: the decisions (APPROVED, REJECTED, RETURNED)
-- and the originator's answer to a return (RESUBMITTED). loan_snapshot is the JSON the action was
-- based on, stored as text so its SHA-256 still matches when it is read back.
CREATE TABLE credit_decisions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    loan_id         BIGINT       NOT NULL,
    action          VARCHAR(32)  NOT NULL,
    reason_code     VARCHAR(64),
    comment         VARCHAR(255) NOT NULL,
    performed_by    VARCHAR(255) NOT NULL,
    performed_at    TIMESTAMP(6) NOT NULL,
    loan_snapshot   TEXT         NOT NULL,
    snapshot_sha256 VARCHAR(64)  NOT NULL,
    CONSTRAINT credit_decisions_pkey PRIMARY KEY (id),
    CONSTRAINT fk_credit_decisions_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT fk_credit_decisions_reason_code FOREIGN KEY (reason_code) REFERENCES credit_reason_codes (code),
    CONSTRAINT ck_credit_decisions_action CHECK (action IN ('APPROVED', 'REJECTED', 'RETURNED', 'RESUBMITTED')),
    CONSTRAINT ck_credit_decisions_reason_code CHECK (action = 'RESUBMITTED' OR reason_code IS NOT NULL)
);
CREATE INDEX idx_credit_decisions_loan_id ON credit_decisions (loan_id);

-- Append-only: a row can be added, never changed or removed.
CREATE FUNCTION refuse_credit_decision_change() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION 'credit_decisions is append-only: % refused', TG_OP;
END;
$$;

CREATE TRIGGER trg_credit_decisions_append_only
    BEFORE UPDATE OR DELETE ON credit_decisions
    FOR EACH ROW EXECUTE FUNCTION refuse_credit_decision_change();

CREATE TRIGGER trg_credit_decisions_no_truncate
    BEFORE TRUNCATE ON credit_decisions
    FOR EACH STATEMENT EXECUTE FUNCTION refuse_credit_decision_change();

-- Decisions taken before this log existed are carried over as they stand on the loan. What they
-- were based on was never captured, and the snapshot says so rather than guessing.
UPDATE loans
SET internal_approval_reason_code = CASE internal_approval_status
                                        WHEN 'APPROVED' THEN 'LEGACY_APPROVAL'
                                        ELSE 'LEGACY_REJECTION' END
WHERE internal_approval_status IN ('APPROVED', 'REJECTED');

INSERT INTO credit_decisions (loan_id, action, reason_code, comment, performed_by, performed_at,
                              loan_snapshot, snapshot_sha256)
SELECT legacy.id, legacy.action, legacy.reason_code, legacy.comment, legacy.performed_by, legacy.performed_at,
       legacy.snapshot, encode(sha256(convert_to(legacy.snapshot, 'UTF8')), 'hex')
FROM (SELECT id,
             internal_approval_status                                             AS action,
             internal_approval_reason_code                                        AS reason_code,
             COALESCE(NULLIF(BTRIM(internal_approval_comment), ''), 'No comment recorded') AS comment,
             COALESCE(NULLIF(BTRIM(internal_approval_by), ''), 'unknown')          AS performed_by,
             COALESCE(internal_approval_date, last_modified_date, created_date)   AS performed_at,
             '{"backfilled":true,"reference":"' || LPAD(id::TEXT, 9, '0') || '","note":"Decided before the credit decision'
                 || ' log existed; the data the decision was based on was not captured"}' AS snapshot
      FROM loans
      WHERE internal_approval_status IN ('APPROVED', 'REJECTED')) AS legacy
ORDER BY legacy.performed_at, legacy.id;
