-- Payslip fraud controls (FR-SSB-007): each payslip is fingerprinted, an application whose payslip
-- raises a concern is held for review, and it goes on to SSB only once a reviewer clears it.

-- payslip_sha256 is the SHA-256 of the payslip's decoded bytes, so the same file matches however it
-- was base64-encoded. The review columns hold the reviewer's one decision on a held application.
ALTER TABLE loans
    ADD COLUMN payslip_sha256         VARCHAR(64),
    ADD COLUMN payslip_review_status  VARCHAR(32),
    ADD COLUMN payslip_reviewed_by    VARCHAR(255),
    ADD COLUMN payslip_reviewed_at    TIMESTAMP(6),
    ADD COLUMN payslip_review_comment VARCHAR(255),
    ADD CONSTRAINT ck_loans_payslip_review_status
        CHECK (payslip_review_status IN ('PENDING', 'CLEARED', 'CONFIRMED'));
CREATE INDEX idx_loans_payslip_sha256 ON loans (payslip_sha256);
CREATE INDEX idx_loans_payslip_review_status ON loans (payslip_review_status);

-- What made an application suspect: one row per finding, naming the other application involved.
CREATE TABLE payslip_fraud_flags (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    loan_id         BIGINT       NOT NULL,
    reason          VARCHAR(64)  NOT NULL,
    matched_loan_id BIGINT,
    detail          VARCHAR(255),
    created_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT payslip_fraud_flags_pkey PRIMARY KEY (id),
    CONSTRAINT fk_payslip_fraud_flags_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT fk_payslip_fraud_flags_matched_loan_id FOREIGN KEY (matched_loan_id) REFERENCES loans (id),
    CONSTRAINT ck_payslip_fraud_flags_reason CHECK (reason IN ('PAYSLIP_REUSED_BY_ANOTHER_APPLICANT',
                                                               'PAYSLIP_REUSED_BY_SAME_APPLICANT',
                                                               'DEDUCTIONS_EXCEED_GROSS_LESS_NET'))
);
CREATE INDEX idx_payslip_fraud_flags_loan_id ON payslip_fraud_flags (loan_id);

-- Fingerprint the payslips already on file, so a new application reusing one of them is caught.
-- Existing applications are not flagged or held: many have been lodged or paid. Hibernate keeps a @Lob
-- string on PostgreSQL as a large object, so the column normally holds the object's OID and the base64
-- is read from the object; a value that is not an OID is taken as the base64 itself. A payload that
-- cannot be read or decoded is left without a fingerprint rather than failing the migration.
DO
$$
    DECLARE
        payslip RECORD;
        payload TEXT;
    BEGIN
        FOR payslip IN SELECT id, payslip_picture
                       FROM loans
                       WHERE payslip_picture IS NOT NULL AND BTRIM(payslip_picture) <> ''
            LOOP
                BEGIN
                    IF payslip.payslip_picture ~ '^[0-9]+$' THEN
                        payload := CONVERT_FROM(LO_GET(payslip.payslip_picture::OID), 'UTF8');
                    ELSE
                        payload := payslip.payslip_picture;
                    END IF;
                    IF payload LIKE 'data:%' AND POSITION(',' IN payload) > 0 THEN
                        payload := SUBSTRING(payload FROM POSITION(',' IN payload) + 1);
                    END IF;
                    UPDATE loans
                    SET payslip_sha256 = ENCODE(SHA256(DECODE(REGEXP_REPLACE(payload, '\s', '', 'g'), 'base64')), 'hex')
                    WHERE id = payslip.id;
                EXCEPTION
                    WHEN OTHERS THEN
                        RAISE NOTICE 'Loan % payslip could not be fingerprinted: %', payslip.id, SQLERRM;
                END;
            END LOOP;
    END
$$;
