-- Loan documents with version history, and a log of every access (FR-SSB-009).
--
-- A document is stored once per version and never changed: a new payslip is version 2, and version 1
-- stays. Every read of a document's content and every upload is logged. Both tables are append-only in
-- the database itself.

-- One row per version of one document of one loan. content holds the decoded file, sha256 its
-- fingerprint (the same SHA-256 FR-SSB-007 matches payslips on).
CREATE TABLE loan_documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    loan_id       BIGINT       NOT NULL,
    document_type VARCHAR(32)  NOT NULL,
    version       INTEGER      NOT NULL,
    origin        VARCHAR(32)  NOT NULL,
    content       BYTEA        NOT NULL,
    content_type  VARCHAR(100) NOT NULL,
    size_bytes    INTEGER      NOT NULL,
    sha256        VARCHAR(64)  NOT NULL,
    reason        VARCHAR(255),
    uploaded_by   VARCHAR(255) NOT NULL,
    uploaded_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT loan_documents_pkey PRIMARY KEY (id),
    CONSTRAINT fk_loan_documents_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT uq_loan_documents_loan_id_document_type_version UNIQUE (loan_id, document_type, version),
    CONSTRAINT ck_loan_documents_document_type
        CHECK (document_type IN ('PAYSLIP', 'NATIONAL_ID', 'SIGNATURE', 'WITNESS_SIGNATURE')),
    CONSTRAINT ck_loan_documents_origin CHECK (origin IN ('APPLICATION', 'AMENDMENT')),
    CONSTRAINT ck_loan_documents_version CHECK (version > 0),
    CONSTRAINT ck_loan_documents_amendment_reason CHECK (origin = 'APPLICATION' OR reason IS NOT NULL)
);
CREATE INDEX idx_loan_documents_sha256 ON loan_documents (sha256);

-- Every view of a document's content and every upload, who and when.
CREATE TABLE loan_document_access_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    loan_id       BIGINT       NOT NULL,
    document_id   BIGINT       NOT NULL,
    document_type VARCHAR(32)  NOT NULL,
    version       INTEGER      NOT NULL,
    action        VARCHAR(32)  NOT NULL,
    performed_by  VARCHAR(255) NOT NULL,
    performed_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT loan_document_access_logs_pkey PRIMARY KEY (id),
    CONSTRAINT fk_loan_document_access_logs_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT fk_loan_document_access_logs_document_id FOREIGN KEY (document_id) REFERENCES loan_documents (id),
    CONSTRAINT ck_loan_document_access_logs_action CHECK (action IN ('VIEW', 'UPLOAD'))
);
CREATE INDEX idx_loan_document_access_logs_loan_id ON loan_document_access_logs (loan_id);

-- Append-only: rows can be added, never changed or removed.
CREATE FUNCTION refuse_append_only_change() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION '% is append-only: % refused', TG_TABLE_NAME, TG_OP;
END;
$$;

CREATE TRIGGER trg_loan_documents_append_only
    BEFORE UPDATE OR DELETE ON loan_documents
    FOR EACH ROW EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_loan_documents_no_truncate
    BEFORE TRUNCATE ON loan_documents
    FOR EACH STATEMENT EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_loan_document_access_logs_append_only
    BEFORE UPDATE OR DELETE ON loan_document_access_logs
    FOR EACH ROW EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_loan_document_access_logs_no_truncate
    BEFORE TRUNCATE ON loan_document_access_logs
    FOR EACH STATEMENT EXECUTE FUNCTION refuse_append_only_change();

-- The documents already on file become version 1 of each, uploaded by the loan's originator when the
-- loan was created. Hibernate kept them on the loan as @Lob strings, which PostgreSQL stores as large
-- objects (the column holds the OID); a value that is not an OID is taken as the base64 itself. The old
-- columns are left as they are, so a document that cannot be read or decoded is reported and stays
-- there rather than being lost.
CREATE FUNCTION migrate_loan_document_bytes(stored TEXT) RETURNS BYTEA
    LANGUAGE plpgsql AS
$$
DECLARE
    payload TEXT;
BEGIN
    IF stored IS NULL OR BTRIM(stored) = '' THEN
        RETURN NULL;
    END IF;
    IF stored ~ '^[0-9]+$' THEN
        payload := CONVERT_FROM(LO_GET(stored::OID), 'UTF8');
    ELSE
        payload := stored;
    END IF;
    IF payload LIKE 'data:%' AND POSITION(',' IN payload) > 0 THEN
        payload := SUBSTRING(payload FROM POSITION(',' IN payload) + 1);
    END IF;
    RETURN DECODE(REGEXP_REPLACE(payload, '\s', '', 'g'), 'base64');
END;
$$;

CREATE FUNCTION migrate_loan_document_content_type(content BYTEA) RETURNS TEXT
    LANGUAGE plpgsql AS
$$
BEGIN
    IF SUBSTRING(content FROM 1 FOR 4) = '\x25504446'::BYTEA THEN
        RETURN 'application/pdf';
    ELSIF SUBSTRING(content FROM 1 FOR 8) = '\x89504e470d0a1a0a'::BYTEA THEN
        RETURN 'image/png';
    ELSIF SUBSTRING(content FROM 1 FOR 3) = '\xffd8ff'::BYTEA THEN
        RETURN 'image/jpeg';
    ELSIF SUBSTRING(content FROM 1 FOR 4) = '\x47494638'::BYTEA THEN
        RETURN 'image/gif';
    END IF;
    RETURN 'application/octet-stream';
END;
$$;

DO
$$
    DECLARE
        loan     RECORD;
        document RECORD;
        bytes    BYTEA;
    BEGIN
        FOR loan IN SELECT id, created_by, created_date, payslip_picture, national_id_picture, signature,
                           witness_signature
                    FROM loans
                    ORDER BY id
            LOOP
                FOR document IN SELECT *
                                FROM (VALUES ('PAYSLIP', loan.payslip_picture),
                                             ('NATIONAL_ID', loan.national_id_picture),
                                             ('SIGNATURE', loan.signature),
                                             ('WITNESS_SIGNATURE', loan.witness_signature)) AS d(document_type, stored)
                    LOOP
                        BEGIN
                            bytes := migrate_loan_document_bytes(document.stored);
                            IF bytes IS NOT NULL AND LENGTH(bytes) > 0 THEN
                                INSERT INTO loan_documents (loan_id, document_type, version, origin, content,
                                                            content_type, size_bytes, sha256, uploaded_by,
                                                            uploaded_at)
                                VALUES (loan.id, document.document_type, 1, 'APPLICATION', bytes,
                                        migrate_loan_document_content_type(bytes), LENGTH(bytes),
                                        ENCODE(SHA256(bytes), 'hex'),
                                        COALESCE(NULLIF(BTRIM(loan.created_by), ''), 'unknown'), loan.created_date);
                            END IF;
                        EXCEPTION
                            WHEN OTHERS THEN
                                RAISE NOTICE 'Loan % % was not carried over (it stays on the loan row): %',
                                    loan.id, document.document_type, SQLERRM;
                        END;
                    END LOOP;
            END LOOP;
    END
$$;

DROP FUNCTION migrate_loan_document_bytes(TEXT);
DROP FUNCTION migrate_loan_document_content_type(BYTEA);
