-- Save-and-resume (FR-SSB-002): an application can be saved part-way and completed later. A draft
-- belongs to the user who started it, holds what has been captured so far, and becomes a loan when it
-- is submitted; the loan's reference is the application reference from then on.

-- application holds the captured fields as JSON, without the documents; it is cleared on submission,
-- when the loan holds them instead. loan_id is set exactly when the draft is submitted.
CREATE TABLE loan_application_drafts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_user_id BIGINT       NOT NULL,
    status        VARCHAR(32)  NOT NULL,
    application   TEXT,
    loan_id       BIGINT,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    submitted_at  TIMESTAMP(6),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT loan_application_drafts_pkey PRIMARY KEY (id),
    CONSTRAINT fk_loan_application_drafts_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_loan_application_drafts_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT uq_loan_application_drafts_loan_id UNIQUE (loan_id),
    CONSTRAINT ck_loan_application_drafts_status CHECK (status IN ('OPEN', 'SUBMITTED')),
    CONSTRAINT ck_loan_application_drafts_submission
        CHECK ((status = 'SUBMITTED') = (loan_id IS NOT NULL AND submitted_at IS NOT NULL))
);
CREATE INDEX idx_loan_application_drafts_owner_user_id_status
    ON loan_application_drafts (owner_user_id, status, updated_at);

-- The documents saved with a draft, one per type, replaced when saved again. On submission they become
-- version 1 of the loan's documents (FR-SSB-009) and are removed here.
CREATE TABLE loan_application_draft_documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    draft_id      BIGINT       NOT NULL,
    document_type VARCHAR(32)  NOT NULL,
    content       BYTEA        NOT NULL,
    content_type  VARCHAR(100) NOT NULL,
    size_bytes    INTEGER      NOT NULL,
    sha256        VARCHAR(64)  NOT NULL,
    uploaded_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT loan_application_draft_documents_pkey PRIMARY KEY (id),
    CONSTRAINT fk_loan_application_draft_documents_draft_id
        FOREIGN KEY (draft_id) REFERENCES loan_application_drafts (id) ON DELETE CASCADE,
    CONSTRAINT uq_loan_application_draft_documents_draft_id_document_type UNIQUE (draft_id, document_type),
    CONSTRAINT ck_loan_application_draft_documents_document_type
        CHECK (document_type IN ('PAYSLIP', 'NATIONAL_ID', 'SIGNATURE', 'WITNESS_SIGNATURE'))
);
