-- Electronic signature of the loan agreement and the SSB deduction authority (FR-SSB-013).

-- The wording of each instrument, one row per published version. A version is never changed: new wording
-- is the next version, and every signed instrument names the version it was rendered from. body carries
-- {{placeholders}} filled from the loan's terms when an applicant signs.
CREATE TABLE instrument_templates (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    instrument_type VARCHAR(32)  NOT NULL,
    version         INTEGER      NOT NULL,
    title           VARCHAR(200) NOT NULL,
    body            TEXT         NOT NULL,
    published_by    VARCHAR(255) NOT NULL,
    published_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT instrument_templates_pkey PRIMARY KEY (id),
    CONSTRAINT uq_instrument_templates_instrument_type_version UNIQUE (instrument_type, version),
    CONSTRAINT ck_instrument_templates_instrument_type
        CHECK (instrument_type IN ('LOAN_AGREEMENT', 'SSB_DEDUCTION_AUTHORITY')),
    CONSTRAINT ck_instrument_templates_version CHECK (version > 0)
);

-- Each instrument as the applicant signed it: the exact text, its fingerprint, the signature it was
-- signed with, and the evidence of the signing (when, by whose session, from which device and address,
-- authenticated how). evidence_sha256 seals the row, so a changed field no longer matches it.
CREATE TABLE loan_signed_instruments (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    loan_id                  BIGINT       NOT NULL,
    instrument_type          VARCHAR(32)  NOT NULL,
    template_version         INTEGER      NOT NULL,
    title                    VARCHAR(200) NOT NULL,
    content                  TEXT         NOT NULL,
    content_sha256           VARCHAR(64)  NOT NULL,
    signature_sha256         VARCHAR(64)  NOT NULL,
    witness_signature_sha256 VARCHAR(64),
    signed_by                VARCHAR(255) NOT NULL,
    signed_at                TIMESTAMP(6) NOT NULL,
    device_id                VARCHAR(128) NOT NULL,
    ip_address               VARCHAR(64)  NOT NULL,
    forwarded_for            VARCHAR(512),
    user_agent               VARCHAR(512),
    authentication_method    VARCHAR(64)  NOT NULL,
    signer_authentication    VARCHAR(64),
    evidence_sha256          VARCHAR(64)  NOT NULL,
    CONSTRAINT loan_signed_instruments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_loan_signed_instruments_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT fk_loan_signed_instruments_template
        FOREIGN KEY (instrument_type, template_version) REFERENCES instrument_templates (instrument_type, version),
    CONSTRAINT uq_loan_signed_instruments_loan_id_instrument_type UNIQUE (loan_id, instrument_type)
);

-- Published wording and signed instruments are evidence: neither is ever changed or removed.
CREATE TRIGGER trg_instrument_templates_append_only
    BEFORE UPDATE OR DELETE ON instrument_templates
    FOR EACH ROW EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_instrument_templates_no_truncate
    BEFORE TRUNCATE ON instrument_templates
    FOR EACH STATEMENT EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_loan_signed_instruments_append_only
    BEFORE UPDATE OR DELETE ON loan_signed_instruments
    FOR EACH ROW EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_loan_signed_instruments_no_truncate
    BEFORE TRUNCATE ON loan_signed_instruments
    FOR EACH STATEMENT EXECUTE FUNCTION refuse_append_only_change();
