-- What the applicant was told, and when (FR-SSB-016). One row per message the lender tried to send about a
-- loan's stage: the text as sent, where it went, the gateway's reference, and whether the gateway accepted it.
-- Kept as evidence that the applicant was told of every stage, so a row is never changed or removed.
CREATE TABLE loan_notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    loan_id           BIGINT       NOT NULL,
    notice            VARCHAR(32)  NOT NULL,
    channel           VARCHAR(16)  NOT NULL,
    recipient         VARCHAR(255),
    message           TEXT         NOT NULL,
    gateway_reference VARCHAR(64)  NOT NULL,
    sent              BOOLEAN      NOT NULL,
    failure_reason    VARCHAR(255),
    attempted_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT loan_notifications_pkey PRIMARY KEY (id),
    CONSTRAINT fk_loan_notifications_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT ck_loan_notifications_notice CHECK (notice IN ('RECEIVED', 'SENT_TO_SSB', 'SSB_CONFIRMED',
        'MORE_INFORMATION_NEEDED', 'RESUBMITTED', 'APPROVED', 'DECLINED', 'PAID', 'PAYOUT_DELAYED', 'NOT_COMPLETED')),
    CONSTRAINT ck_loan_notifications_channel CHECK (channel IN ('SMS')),
    CONSTRAINT ck_loan_notifications_outcome CHECK (sent OR failure_reason IS NOT NULL)
);
CREATE INDEX idx_loan_notifications_loan_id ON loan_notifications (loan_id, id);

CREATE TRIGGER trg_loan_notifications_append_only
    BEFORE UPDATE OR DELETE ON loan_notifications
    FOR EACH ROW EXECUTE FUNCTION refuse_append_only_change();
CREATE TRIGGER trg_loan_notifications_no_truncate
    BEFORE TRUNCATE ON loan_notifications
    FOR EACH STATEMENT EXECUTE FUNCTION refuse_append_only_change();
